# -*- coding: utf-8 -*-
"""london_stock_exchange_FTSE100.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tZe6LY6Y6k-ClGJbB7OygNH73oqTVlAL
"""

import yfinance as yf
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

#https://www.hl.co.uk/shares/stock-market-summary/ftse-small-cap/top-volume

tickers=["LLOY.L","VOD.L","RR.L","^FTSE"]

end_date=datetime.today()

start_date=end_date-timedelta(days=2*365)

close_df=pd.DataFrame()

for ticker in tickers:
  data = yf.download(ticker,start_date,end=end_date)
  close_df[ticker]=data['Close']

close_df

returns = close_df.pct_change()
returns

mean_returns=returns.mean()
mean_returns

variance=returns.var()
variance

cov_matrix=returns.cov()
cov_matrix

proportions=np.array([0.5,0.2,0.3])
stock_returns=mean_returns[:-1]
portfolio_return= stock_returns.dot(proportions)*252
portfolio_return

portfolio_variance = np.dot(proportions.T, np.dot(cov_matrix.iloc[:-1,:-1], proportions))*252
portfolio_variance

betas={}

for ticker in tickers[:-1]:
  covariance = cov_matrix.loc [ticker,"^FTSE"]
  market_variance=variance[-1]
  beta = covariance/ market_variance
  betas[ticker] = beta

for ticker,beta in betas.items():
  print(f"{ticker}: Beta = {beta:.4f}")

mes_actions=returns
mes_actions.plot(title="Market and stocks Return History")

betas_series = pd.Series(betas)
portfolio_beta = betas_series.dot(proportions)
portfolio_beta

pip install fredapi

from fredapi import Fred
fred=Fred(api_key="6c37dd551d9d51704a86e9abc76034d4")
rate=fred.get_series_latest_release("IRLTLT01GBM156N")/100
rf=rate.iloc[-1]
rf

excess_return=portfolio_return-rf
excess_return

portfolio_volatility=np.sqrt(portfolio_variance)
portfolio_volatility

sharpe_ratio=excess_return/portfolio_volatility
sharpe_ratio

treynor_ratio=excess_return/portfolio_beta
treynor_ratio